apiVersion: batch/v1
kind: CronJob
metadata:
  name: hazard-modeling
  namespace: hazard-modeling
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hazard-modeling
            image: ${DOCKERHUB_USERNAME}/hazard-modeling:latest
            resources:
              requests:
                memory: "2Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "1000m"
            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hazard-modeling-secrets
                  key: API_KEY
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hazard-modeling-secrets
                  key: DATABASE_PASSWORD
            volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: output-volume
              mountPath: /app/output
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: hazard-data-pvc
          - name: output-volume
            persistentVolumeClaim:
              claimName: hazard-output-pvc
          imagePullSecrets:
          - name: docker-registry-credentials
          restartPolicy: OnFailure