apiVersion: batch/v1
kind: CronJob
metadata:
  name: hazard-modeling
  namespace: hazard-modeling
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hazard-modeling
            image: localhost:5000/hazard-modeling:20250412-130607
            resources:
              requests:
                memory: "2Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "1000m"
            volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: output-volume
              mountPath: /app/output
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: hazard-data-pvc
          - name: output-volume
            persistentVolumeClaim:
              claimName: hazard-output-pvc
          restartPolicy: OnFailure