apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hazard-data-pvc
  namespace: hazard-modeling
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hazard-output-pvc
  namespace: hazard-modeling
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi