name: Sync ArgoCD Application

on:
  # Trigger after the docker build workflow completes
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches: [argocd]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync_argocd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: argocd

      # Install ArgoCD CLI
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64

      # Login to ArgoCD
      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      # Sync ArgoCD application
      - name: Sync ArgoCD Application
        run: |
          argocd app sync hazard-modeling --prune
          argocd app wait hazard-modeling --health